[localstack.aws.provider]
transfer = localstack.services.providers:transfer

[localstack.cloudformation.resource_providers]
# CloudFormation resource providers are registered by downstream packages

[localstack.hooks.on_infra_ready]
_run_init_scripts_on_ready = localstack.runtime.init:_run_init_scripts_on_ready

[localstack.hooks.on_infra_shutdown]
_run_init_scripts_on_shutdown = localstack.runtime.init:_run_init_scripts_on_shutdown
run_on_after_service_shutdown_handlers = localstack.runtime.shutdown:run_on_after_service_shutdown_handlers
run_shutdown_handlers = localstack.runtime.shutdown:run_shutdown_handlers
shutdown_services = localstack.runtime.shutdown:shutdown_services
stop_server = localstack.dns.plugins:stop_server

[localstack.hooks.on_infra_start]
_patch_botocore_endpoint_in_memory = localstack.aws.client:_patch_botocore_endpoint_in_memory
_patch_botocore_json_parser = localstack.aws.client:_patch_botocore_json_parser
_patch_cbor2 = localstack.aws.client:_patch_cbor2
_run_init_scripts_on_start = localstack.runtime.init:_run_init_scripts_on_start
apply_aws_runtime_patches = localstack.aws.patches:apply_aws_runtime_patches
apply_runtime_patches = localstack.runtime.patches:apply_runtime_patches
delete_cached_certificate = localstack.plugins:delete_cached_certificate
deprecation_warnings = localstack.plugins:deprecation_warnings
eager_load_services = localstack.services.plugins:eager_load_services
init_response_mutation_handler = localstack.aws.handlers.response:init_response_mutation_handler
register_swagger_endpoints = localstack.http.resources.swagger.plugins:register_swagger_endpoints
setup_dns_configuration_on_host = localstack.dns.plugins:setup_dns_configuration_on_host
start_dns_server = localstack.dns.plugins:start_dns_server

[localstack.init.runner]
py = localstack.runtime.init:PythonScriptRunner
sh = localstack.runtime.init:ShellScriptRunner

[localstack.lambda.runtime_executor]
# Lambda runtime executors are registered by downstream packages

[localstack.openapi.spec]
localstack = localstack.plugins:CoreOASPlugin

[localstack.runtime.components]
aws = localstack.aws.components:AwsComponents

[localstack.runtime.server]
hypercorn = localstack.runtime.server.plugins:HypercornRuntimeServerPlugin
twisted = localstack.runtime.server.plugins:TwistedRuntimeServerPlugin
